name: Assign Issues to Project Board

on:
  issues:
    types: [opened, edited]

jobs:
  assign-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Assign issue to project board
        uses: peter-evans/issue-assign-to-project@v2

        with:
          project-url: https://github.com/orgs/JonCodyDev-Services/projects/2
          issue-number: ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.COMPANY_REPO_ACTIONS_TOKEN }}  # Use GitHub token from secrets

