name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run tests (if you have tests set up)
      - name: Run tests
        run: npm test

      # Build project
      - name: Build project
        run: npm run build

      # Modify files (if required)
      - name: Modify files
        run: echo "Changes made by the workflow" >> file.txt

      # Commit the changes (if needed)
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update file after build"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # Final message after build
      - name: Final message
        run: |
          echo "Project built, tests passed."
