name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  issues:
    types: [opened, assigned]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          if [[ `git diff --cached --stat` != '' ]]; then
            git commit -m "Update file after build"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
          else
            echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  add_issue_to_project:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Debug event details
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Event Action: ${{ github.event.action }}"
          echo "Full Event Payload: ${{ toJson(github.event) }}"

      - name: Check if condition met
        run: |
          if [[ "${{ github.event_name }}" == "issues" && ( "${{ github.event.action }}" == "opened" || "${{ github.event.action }}" == "assigned" ) ]]; then
            echo "Condition met. Proceeding to add issue to project."
          else
            echo "Condition NOT met. Job will be skipped."
          fi

      - name: Add issue to project board
        if: ${{ github.event_name == 'issues' && (github.event.action == 'opened' || github.event.action == 'assigned') }}
        uses: actions/github-script@v5
        with:
          script: |
            const issue_number = context.payload.issue.number;
            const project_id = '2';  # Replace this with your GitHub Project ID
            const column_name = 'Backlog';  # Default column to add the issue to (e.g., "Backlog")
            
            try {
              const columns = await github.rest.projects.listColumns({
                project_id: project_id,
              });
              
              const targetColumn = columns.data.find(column => column.name === column_name);
              if (targetColumn) {
                await github.rest.projects.createCard({
                  column_id: targetColumn.id,
                  content_id: issue_number,
                  content_type: 'Issue',
                });
                console.log(`Issue #${issue_number} added to "${column_name}"`);
              } else {
                console.log(`Column "${column_name}" not found in project ${project_id}`);
              }
            } catch (error) {
              console.error('Error adding issue to project:', error);
              throw error;
            }
        env:
          GITHUB_TOKEN: ${{ secrets.PROJECT_ACCESS_TOKEN }}  # Use the secret for the token
